spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  application:
    name: product-server
  # 数据库连接和数据库连接池配置
  datasource:
    hikari:
      connection-test-query: select 1
      max-lifetime: 180000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 36000
      connection-timeout: 50000
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: url
    username: username
    password: password
  redis:
    host: localhost
    # password:
    port: 6379
    database: 0
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8


# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.platform.productserver.entity
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 9501
  tomcat:
    accept-count: 100
    max-connections: 8192
    threads:
      max: 200

# 日志记录
logging:
  level:
     com.platform: debug


