spring:
  application:
    name: boot-rabbitmq
  profiles:
    active: dev
  rabbitmq:
    # addresses: localhost http://192.168.0.102:15674 http://192.168.0.102:15672 guest/guest
    addresses: localhost:5678
    # port: 5672
    # host: 192.168.0.102
    # port: 5678
    username: guest
    password: guest
    virtual-host: bootapp
    # 确认消息已经发送到交换机 exchange
    # publisher-confirms: true
    # 确认消息已经发送到队列 queue
    # publisher-returns: true
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        initial-interval: 1000ms
        enabled: true
        multiplier: 3
        max-attempts: 5
        max-interval: 3000ms


