spring:
  profiles:
    active: dev
  application:
      name: order-server
  cloud:
     nacos:
       discovery:
           server-addr: localhost:8848
           namespace: 163c702f-c805-42f2-a1e1-a491f086f3a2
           group: springboot-oauth


server:
  port: 9301

app:
  wxpay:
    mch-id: mcd_id
    mch-serial-no: serial_no
    private-key-path: apiclient_key.pem
    api-v3-key: v3_key
    appid: app_id
    domain: https://api.mch.weixin.qq.com
    notify-domain: https://www.return.com
    partner-key: parter_key


alipay:
  private-key: xxx
  app-cert-path : xx
  alipay-cert-path: xx
  alipay-root-cert-path: xx
  app-id: xx
  notify: xx
  charset: UTF-8
  sign-type: RSA2
  format: json
  gateway: https://openapi.alipay.com/gateway.do
